# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160727_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='backend.Category'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='/home/nht/playground/reactnative/chanqadimv1server/chanqadimv1server/../media/default.jpg', upload_to=''),
        ),
    ]
