# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_auto_20161007_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
