# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_bundle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(default='/home/nht/playground/reactnative/chanqadimv1server/chanqadimv1server/../media/default.jpg', upload_to='')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.Bundle')),
            ],
        ),
    ]
